baseurl: "http://4g.noobadmin.de/"
languageCode: "de-de"
title: "Noobadmin 4G"
theme: "hyde-x"
path: "blog"
paginatePath: "path"
publishdir: "public"
metaDataFormat: "yaml"

permalinks:
  post: "blog/:year/:month/:day/:filename/"

author:
  name: "Jan Brand"

params:
 Description: "Yeah!"
 Copyright: "&copy; 2015 Jan Brand.<br/>CC BY-NC-SA Some rights reserved."
 theme: "theme-base-0d"
 truncate: false
 tagline: "Blog all the things"
 github: "https://github.com/uffsalot"
 twitter: "https://twitter.com/P0stbote"
 youtube: "https://www.youtube.com/user/Postbotze10"