baseurl: "https://4g.noobadmin.de/"
languageCode: "de-de"
title: "Noobadmin 4G"
theme: "hyde-x"
path: "blog"
paginatePath: "path"
publishdir: "public"
metaDataFormat: "yaml"

permalinks:
  post: "blog/:year/:month/:day/:filename/"

author:
  name: "Jan"

params:
 Description: "Yeah!"
 Copyright: "&copy; 2015 Jan Brand.<br/>CC BY-NC-SA Some rights reserved."
 theme: "theme-base-0d"
 truncate: false
 tagline: "Blog all the things"
 github: "https://github.com/uffsalot"
 twitter: "https://twitter.com/uffsalot"
 youtube: "https://www.youtube.com/user/Postbotze10"

menu:
 main:
 - name: "Technik"
   weight: 50
   identifier: "Technik"
   url: "/Technik/"
 - name: "Impressum"
   weight: 100
   identifier: "Impressum"
   url: "/Impressum/"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

